openapi: 3.0.0
info:
  title: FitGPT API
  version: 1.0.0
  description: API för att hämta din Fitbit-data till GPT
servers:
  - url: https://fitgpt-2364.onrender.com

paths:
  /data:
    get:
      summary: Hämta dagens eller en specifik dags Fitbit-data
      parameters:
        - name: date
          in: query
          required: false
          description: Datum i formatet YYYY-MM-DD. Om inget anges hämtas "today".
          schema:
            type: string
      responses:
        '200':
          description: JSON med Fitbit-data för dagen

  /history:
    get:
      summary: Hämta sammanfattning av tidigare dagar
      parameters:
        - name: days
          in: query
          required: false
          description: Antal dagar bakåt att hämta (default: 7)
          schema:
            type: integer
      responses:
        '200':
          description: Lista med datum, steg, kalorier, sömn
